export const defaultTheme = {
  base: {
    white: '#FFFFFF',
    background: '#FAFAFA',
    card: '#F3F2F2',
    input: '#EDEDED',
    button: '#E6E5E5',
    hover: '#D7D5D5',
    label: '#8D8686',
    text: '#574F4D',
    subtitle: '#403937',
    title: '#272221',
  },
  brand: {
    purpleDark: '#4B2995',
    purple: '#8047F8',
    purpleLight: '#EBE5F9',
    yellowDark: '#C47F17',
    yellow: '#DBAC2C',
    yellowLight: '#F1E9C9',
  },
  font: {
    title: '"Baloo 2", sans-serif',
    text: '"Roboto", sans-serif',
    titleWeight: {
      boldOne: 700,
      boldTwo: 800,
    },
    textWeight: {
      regular: 400,
      bold: 700,
    },
  },
  sizes: {
    xsmall: '0.6rem',
    small: '0.8rem',
    medium: '1rem',
    large: '1.2rem',
    xlarge: '2.0rem',
    xxlarge: '3.0rem',
  },
  spacings: {
    xsmall: '0.4rem',
    small: '0.8rem',
    medium: '1.2rem',
    large: '1.8rem',
    xlarge: '2.4rem',
    xxlarge: '3.0rem',
  },
  borderRadius: '4px',
}
